### ISSUE TITLE
Compatibility with eval-sexp-fu.el

### ISSUE THREAD

**Issue by Alexander-Miller** [rswgnu/rsw-elisp#1]
[eval-sexp-fu.el](https://www.emacswiki.org/emacs/eval-sexp-fu.el) defines a minor mode that flashes evaluated s-expressions. It's a great visual helper, and is part of spacemacs' default setup. It'd be great if this package could include a similar flashing mechanism. 

Using eval-sexp-fu is probably easiest, but since the code is on emacswiki and was last changed in 2013 it might just be easier to do your own thing (using pulse worked quite well in treemacs).

**Comment by rswgnu** [comment]
I'll take a look.  The package already supports eros which shows the result at point until some other input comes in.  But as you say, this would be useful for spacemacs users.

-- Bob

**Comment by rswgnu** [comment]
I tried highlight.el under Emacs 26 but it did not seem to work out of the box.  It mentions that it utilizes many other libraries, so it may not be compatible.  Try the eros package; it seems much simpler.  Let me know if that does what you want or not and we can go from there.

**Comment by rswgnu** [comment]
I see how the eval-sexp-fu package works now and will see if it can be integrated straightforwardly with rsw-elisp.el.

**Comment by rswgnu** [comment]
This has been added to release 1.0.5.
